jwt.access.expiration=300000
jwt.refresh.expiration=604800000
jwt.reset.expiration=1209600000
jwt.secretKey=9a4f2c8d3b7a1e6f5c8b9a2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f=

spring.redis.host=${REDIS_HOST:localhost}
spring.redis.post=${REDIS_PORT:6379}